import type { ApsRule } from "@/lib/firestore/types";
import { CURRENT_ACADEMIC_YEAR } from "./academicYear";

const VERIFIED_ON = "2026-07-27";
const ACADEMIC_YEAR = CURRENT_ACADEMIC_YEAR;

const NSC_7_POINT_BANDS = [
  { minPercent: 80, maxPercent: 100, points: 7 },
  { minPercent: 70, maxPercent: 79, points: 6 },
  { minPercent: 60, maxPercent: 69, points: 5 },
  { minPercent: 50, maxPercent: 59, points: 4 },
  { minPercent: 40, maxPercent: 49, points: 3 },
  { minPercent: 30, maxPercent: 39, points: 2 },
  { minPercent: 0, maxPercent: 29, points: 1 },
];

export const SEED_APS_RULES: ApsRule[] = [
  {
    id: "ump-aps-rule",
    institutionId: "ump",
    scaleName: "UMP Admission Point Score (APS)",
    formulaType: "pointBandSum",
    bands: NSC_7_POINT_BANDS,
    usesRawPercentage: false,
    loPolicy: "halfWeight",
    bestNSubjects: 7,
    excludedSubjects: [],
    mathLitPolicy: "excludedForSomeProgrammes",
    nbtPolicy: "none",
    bonusRules: [],
    notes:
      "UMP's official Undergraduate Programmes brochure: 'The prescribed seven subjects are the subjects to be used in calculating the APS. The APS achievement rating of Life Orientation is divided by two.'",
    sourceUrl:
      "https://www.ump.ac.za/getattachment/Study-with-us/Application-Process/Online-Applications/Undergraduate-Programmes.pdf.aspx",
    verifiedOn: VERIFIED_ON,
    academicYear: ACADEMIC_YEAR,
  },
  {
    id: "up-aps-rule",
    institutionId: "up",
    scaleName: "UP Admission Point Score (APS)",
    formulaType: "pointBandSum",
    bands: NSC_7_POINT_BANDS,
    usesRawPercentage: false,
    loPolicy: "exclude",
    bestNSubjects: 6,
    excludedSubjects: [],
    mathLitPolicy: "excludedForSomeProgrammes",
    nbtPolicy: "none",
    bonusRules: [],
    maxScore: 42,
    notes: "UP 2027 Prospectus: Best 6 subjects excluding Life Orientation.",
    sourceUrl: "https://www.up.ac.za/students/programme-calculator",
    verifiedOn: VERIFIED_ON,
    academicYear: ACADEMIC_YEAR,
  },
  {
    id: "wits-aps-rule",
    institutionId: "wits",
    scaleName: "Wits Admission Point Score (APS)",
    formulaType: "pointBandSum",
    bands: NSC_7_POINT_BANDS,
    usesRawPercentage: false,
    loPolicy: "include",
    bestNSubjects: 7,
    excludedSubjects: [],
    mathLitPolicy: "excludedForSomeProgrammes",
    nbtPolicy: "none",
    bonusRules: [],
    notes: "Wits: 7 subjects including Life Orientation + bonus points for high marks.",
    sourceUrl: "https://www.wits.ac.za/undergraduate/entry-requirements/",
    verifiedOn: VERIFIED_ON,
    academicYear: ACADEMIC_YEAR,
  },
  {
    id: "uj-aps-rule",
    institutionId: "uj",
    scaleName: "UJ Admission Point Score (APS)",
    formulaType: "pointBandSum",
    bands: NSC_7_POINT_BANDS,
    usesRawPercentage: false,
    loPolicy: "exclude",
    bestNSubjects: 6,
    excludedSubjects: [],
    mathLitPolicy: "excludedForSomeProgrammes",
    nbtPolicy: "none",
    bonusRules: [],
    notes: "UJ: Best 6 subjects excluding Life Orientation.",
    sourceUrl: "https://www.uj.ac.za/",
    verifiedOn: VERIFIED_ON,
    academicYear: ACADEMIC_YEAR,
  },
  {
    id: "tut-aps-rule",
    institutionId: "tut",
    scaleName: "TUT Admission Point Score (APS)",
    formulaType: "pointBandSum",
    bands: NSC_7_POINT_BANDS,
    usesRawPercentage: false,
    loPolicy: "exclude",
    bestNSubjects: 6,
    excludedSubjects: [],
    mathLitPolicy: "excludedForSomeProgrammes",
    nbtPolicy: "none",
    bonusRules: [],
    notes: "TUT: Best 6 subjects excluding Life Orientation.",
    sourceUrl: "https://www.tut.ac.za/",
    verifiedOn: VERIFIED_ON,
    academicYear: ACADEMIC_YEAR,
  },
];
