import { CareerExplorer } from '@/components/career/CareerExplorer';
import { Compass, Sparkles } from 'lucide-react';

export const metadata = {
  title: 'Career Guidance — UCAG',
  description: 'Explore UMP career pathways with live AI analysis powered by Google Gemini.',
};

export default function CareerPage() {
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8 space-y-6">
      <div className="flex items-start justify-between flex-wrap gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Compass size={22} className="text-navy-700" />
            <h1 className="text-2xl font-extrabold text-navy-900 dark:text-white">Career Guidance</h1>
          </div>
          <p className="text-sm text-navy-500 dark:text-navy-400 max-w-xl">
            Enter your APS and subjects to see which UMP courses you qualify for, then get a personalised
            career narrative generated by Google Gemini AI.
          </p>
        </div>
        <div className="flex items-center gap-1.5 bg-uorange-50 border border-uorange-200 rounded-full px-3 py-1 text-xs font-semibold text-uorange-700">
          <Sparkles size={11} />
          Live Gemini AI · gemini-2.5-flash
        </div>
      </div>

      <CareerExplorer />
    </div>
  );
}
