import "server-only";
import model from "./model.json";
import { tokenize } from "./shared";

/**
 * Runtime inference for the bursary/internship scam classifier. The
 * trained weights live in model.json (generated by
 * scripts/train-bursary-scam-model.mts) and are imported directly rather
 * than read from disk at request time -- this needs to work in a Vercel
 * serverless function with no filesystem write access and no ML runtime
 * dependency, the same constraint lib/aps/engine.ts is built around.
 *
 * This is a probability, not a verdict -- it is deliberately NOT wired to
 * auto-reject a listing on its own except at a very high, conservative
 * threshold (see bursarySafety.ts's ML_HIGH_RISK_THRESHOLD). Bursaries
 * are always-high-risk per lib/ingestion/route.ts regardless of
 * confidence, so every listing already goes to human review; this score
 * is a second opinion to help that review catch scam phrasing the
 * deterministic keyword list in bursarySafety.ts misses, not a
 * replacement for it. See trainingData.ts for the real limitation: this
 * was trained on hand-written examples, not a scraped real-world corpus.
 */

const wordIndex = new Map(model.vocabulary.map((word, i) => [word, i]));

/** Returns P(this text is a scam listing), in [0, 1]. */
export function scoreBursaryScamRisk(text: string): number {
  let scamScore = model.classLogPrior.scam;
  let legitScore = model.classLogPrior.legitimate;

  for (const token of tokenize(text)) {
    const idx = wordIndex.get(token);
    if (idx === undefined) continue;
    scamScore += model.wordLogProb.scam[idx];
    legitScore += model.wordLogProb.legitimate[idx];
  }

  const max = Math.max(scamScore, legitScore);
  const scamExp = Math.exp(scamScore - max);
  const legitExp = Math.exp(legitScore - max);
  return scamExp / (scamExp + legitExp);
}

export const bursaryScamModelMetadata = {
  trainedAt: model.trainedAt,
  metrics: model.metrics,
};
